const DEFAULT_BORDER_RADIUS = 8;

// LOGIN SCREEN
const LOGIN_EMAIL_PLACEHOLDER = 'Enter your email';
const LOGIN_PASSWORD_PLACEHOLDER = 'Enter your password';

export {
  LOGIN_EMAIL_PLACEHOLDER,
  LOGIN_PASSWORD_PLACEHOLDER,
  DEFAULT_BORDER_RADIUS,
};
